### ISSUE TITLE
无法直连，网络错误

### ISSUE THREAD

**Issue by xuhuantianlun** [UjuiUjuMandan/EhViewer#10] opened 2023-10-28 10:09 UTC
### 复现步骤 / Step to reproduce

进入列表后，报网络错误
![Screenshot_2023-10-28-18-01-16-55_f2f1746601bf3b868d00d5efaf12e601](https://github.com/UjuiUjuMandan/EhViewer/assets/107929065/9502e204-b11c-44a5-a5ad-7e84d782a3d7)

### 预期行为 / Expected behaviour

是否需要设置才可以直连

### 实际行为 / Actual Behaviour

![Screenshot_2023-10-28-18-03-40-98_f2f1746601bf3b868d00d5efaf12e601](https://github.com/UjuiUjuMandan/EhViewer/assets/107929065/97b7d650-4891-4ca4-9865-618744a3afeb)
![Screenshot_2023-10-28-18-01-16-55_f2f1746601bf3b868d00d5efaf12e601](https://github.com/UjuiUjuMandan/EhViewer/assets/107929065/d7666f3c-3b76-407c-8a44-c076671e1c46)

### EhViewer 版本号 / EhViewer version code

1.8.10.2censorcircum

### EhViewer CI 版本 / EhViewer CI Version

03f3b9c

### Android 系统版本 / Android version

PEDM00_13.1.0.191

### 设备型号 / Device model

Oppo findx3

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment] 2023-10-28 10:10
Duplicate of #1 .

**Closed by UjuiUjuMandan** 2023-10-28 10:10 UTC
Labels: bug
