### ISSUE TITLE
直连显示net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by ujfadndna** [UjuiUjuMandan/EhViewer#20] opened 2023-11-12 03:01 UTC
### 复现步骤 / Step to reproduce

重新安装CC版本

### 预期行为 / Expected behaviour

直连

### 实际行为 / Actual Behaviour

显示net::ERR_CONNECTION_RESET

### 应用日志 / App logs

TIME=2023-11-12-10-20-57-058

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.8.11.1-gms
VersionCode=180045
CommitSha=7e90555
BuildTime=2023/11/01 15:34

======== DeviceInfo ========
BOARD=oppo6771_17197
BOOTLOADER=unknown
BRAND=OPPO
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=PACM00
DISPLAY=PACM00_11_F.27
FINGERPRINT=OPPO/PACM00/PACM00:10/QP1A.190711.020/2021050100:user/release-keys
HARDWARE=mt6771
HOST=CP-ubuntu-123
ID=QP1A.190711.020
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=OPPO
MODEL=PACM00
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=PACM00
RADIO=unknown
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=release-keys
TIME=1619345213000
TYPE=user
UNKNOWN=unknown
USER=root
ACTIVE_CODENAMES=
BASE_OS=OPPO/PACM00/PACM00:10/QP1A.190711.020/1608710200:user/release-keys
CODENAME=REL
FIRST_SDK_INT=27
INCREMENTAL=2021050100
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=10
RESOURCES_SDK_INT=29
SDK=29
SDK_INT=29
SECURITY_PATCH=2021-04-05
MEMORY=16.3 MiB
MEMORY_NATIVE=25.0 MiB
MEMORY_MAX=384.0 MiB
MEMORY_TOTAL=5.5 GiB

======== CrashInfo ========
java.lang.RuntimeException: java.lang.NoSuchMethodException: oD.values []
	at java.lang.Enum.enumValues(Enum.java:270)
	at java.lang.Enum.access$000(Enum.java:61)
	at java.lang.Enum$1.create(Enum.java:277)
	at java.lang.Enum$1.create(Enum.java:275)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
	at java.lang.Enum.getSharedConstants(Enum.java:289)
	at java.lang.Enum.valueOf(Enum.java:243)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1841)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at android.os.Parcel.readSerializable(Parcel.java:3150)
	at android.os.Parcel.readValue(Parcel.java:2933)
	at android.os.Parcel.readListInternal(Parcel.java:3323)
	at android.os.Parcel.readArrayList(Parcel.java:2466)
	at android.os.Parcel.readValue(Parcel.java:2903)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3260)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.BaseBundle.keySet(BaseBundle.java:562)
	at V4.a(Unknown Source:209)
	at androidx.compose.ui.platform.c.a(Unknown Source:170)
	at androidx.compose.ui.platform.c.m(Unknown Source:27)
	at Ln.m(Unknown Source:53)
	at nr.n(Unknown Source:4)
	at tv.r(Unknown Source:229)
	at androidx.compose.ui.platform.c.a(Unknown Source:144)
	at androidx.compose.ui.platform.c.m(Unknown Source:15)
	at Ln.m(Unknown Source:53)
	at GA.e1(Unknown Source:14)
	at xp.s(Unknown Source:132)
	at xp.k(Unknown Source:10)
	at Gp.o(Unknown Source:20)
	at wy0.a(Unknown Source:25)
	at Gp.c(Unknown Source:10)
	at androidx.compose.ui.platform.d.n(Unknown Source:98)
	at androidx.compose.ui.platform.WrappedComposition.c(Unknown Source:14)
	at androidx.compose.ui.platform.WrappedComposition.k(Unknown Source:18)
	at H90.a(Unknown Source:22)
	at androidx.lifecycle.a.a(Unknown Source:215)
	at androidx.compose.ui.platform.d.n(Unknown Source:67)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:98)
	at android.view.View.dispatchAttachedToWindow(View.java:19857)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2051)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8456)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
	at android.view.Choreographer.doCallbacks(Choreographer.java:889)
	at android.view.Choreographer.doFrame(Choreographer.java:816)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1050)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7830)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
Caused by: java.lang.NoSuchMethodException: oD.values []
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getDeclaredMethod(Class.java:2050)
	at java.lang.Enum.enumValues(Enum.java:267)
	... 62 more
java.lang.NoSuchMethodException: oD.values []
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getDeclaredMethod(Class.java:2050)
	at java.lang.Enum.enumValues(Enum.java:267)
	at java.lang.Enum.access$000(Enum.java:61)
	at java.lang.Enum$1.create(Enum.java:277)
	at java.lang.Enum$1.create(Enum.java:275)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
	at java.lang.Enum.getSharedConstants(Enum.java:289)
	at java.lang.Enum.valueOf(Enum.java:243)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1841)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at android.os.Parcel.readSerializable(Parcel.java:3150)
	at android.os.Parcel.readValue(Parcel.java:2933)
	at android.os.Parcel.readListInternal(Parcel.java:3323)
	at android.os.Parcel.readArrayList(Parcel.java:2466)
	at android.os.Parcel.readValue(Parcel.java:2903)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3260)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.BaseBundle.keySet(BaseBundle.java:562)
	at V4.a(Unknown Source:209)
	at androidx.compose.ui.platform.c.a(Unknown Source:170)
	at androidx.compose.ui.platform.c.m(Unknown Source:27)
	at Ln.m(Unknown Source:53)
	at nr.n(Unknown Source:4)
	at tv.r(Unknown Source:229)
	at androidx.compose.ui.platform.c.a(Unknown Source:144)
	at androidx.compose.ui.platform.c.m(Unknown Source:15)
	at Ln.m(Unknown Source:53)
	at GA.e1(Unknown Source:14)
	at xp.s(Unknown Source:132)
	at xp.k(Unknown Source:10)
	at Gp.o(Unknown Source:20)
	at wy0.a(Unknown Source:25)
	at Gp.c(Unknown Source:10)
	at androidx.compose.ui.platform.d.n(Unknown Source:98)
	at androidx.compose.ui.platform.WrappedComposition.c(Unknown Source:14)
	at androidx.compose.ui.platform.WrappedComposition.k(Unknown Source:18)
	at H90.a(Unknown Source:22)
	at androidx.lifecycle.a.a(Unknown Source:215)
	at androidx.compose.ui.platform.d.n(Unknown Source:67)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:98)
	at android.view.View.dispatchAttachedToWindow(View.java:19857)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3515)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2051)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8456)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
	at android.view.Choreographer.doCallbacks(Choreographer.java:889)
	at android.view.Choreographer.doFrame(Choreographer.java:816)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1050)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7830)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1-cc

### EhViewer CI 版本 / EhViewer CI Version

42297a3

### Android 系统版本 / Android version

10

### 设备型号 / Device model

OPPO R15

### SoC 型号 / Soc model

联发科Helio P60

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment] 2023-11-12 03:55
Duplicate of #1.
自选 Cloudflare IP 或者关了 cronet 用域名前置。

**Closed by UjuiUjuMandan** 2023-11-12 03:55 UTC
Labels: bug

**Comment by UjuiUjuMandan** [comment] 2023-11-12 03:57
还有，日志是错的，都不是这个版本。下次传日志请把导出的 .zip 文件发上来。

**Comment by ujfadndna** [comment] 2023-11-12 04:18
> 还有，日志是错的，都不是这个版本。下次传日志请把导出的 .zip 文件发上来。

感谢
